
[functions.whatsapp-cloud-bot]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-cloud-bot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-cloud-bot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-cloud-bot/*.html" ]

[functions.whatsapp-twilio-bot]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-twilio-bot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-twilio-bot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-twilio-bot/*.html" ]

[functions.whatsapp-whatchimp-bot]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-whatchimp-bot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-whatchimp-bot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-whatchimp-bot/*.html" ]

[functions.telegram-bot]
enabled = true
verify_jwt = true
import_map = "./functions/telegram-bot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/telegram-bot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/telegram-bot/*.html" ]
